name:                cligmm
version:             0.1.0.0
github:              "TheDrawingCoder-Gamer/GMMChallenge"
license:             GPL-3
author:              "BulbyVR"
copyright:           "2022 BulbyVR"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell#readme>

dependencies:
- base >= 4.7 && < 5


executables:
 cligmm-exe:
    main:                cligmm.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - req
    - text
    - zip
    - modern-uri
    - bytestring
    - directory
